### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by MuturiIsaac** [Panther-12/studentManagementSystem#2]
menu bar may be drop down list to display units and scores for student accounts  and lectures as well.

**Comment by Panther-12** [comment]
If you can get sample templates or images share so i can get a glimpse of what is expected

**Comment by Panther-12** [comment]
This issue will be closed after we get the samples

**Comment by MuturiIsaac** [comment]
[](url)
![Screenshot (39)](https://user-images.githubusercontent.com/125857937/224485621-1cd73dbe-60bb-4401-b566-52dba7ceec55.png)

**Comment by MuturiIsaac** [comment]
> This issue will be closed after we get the samples

okay working on that.

**Comment by victorpreston** [comment]
I do think this issue was resolved guys
